### ISSUE TITLE
Masalah pada scroll

### ISSUE THREAD

**Issue by zakizulham** [aslab-math-ui/modul-prak#1]
Description : Scroll pada mobile UX mengalami kendala.Bentuk  [https://youtube.com/shorts/vPg_KwGle2Q?si=D6ZE4nOhxZKj9znM](video) yang bisa menjelaskan masalah lebih lanjut.

**Comment by BismaBRJ** [comment]
Halaman yang dibahas:

Modul 1 Metode Numerik 2024 Genap

Kendala:

UX scroll kode di browser mobile terganggu.

1. Setelah halaman ini dibuka, halaman bisa di-zoom out (artinya tidak langsung full width ketika baru dibuka). Hal ini seringkali--ternyata kali ini juga--disebabkan oleh adanya penulisan LaTeX di halaman tersebut yang terlalu panjang secara horizontal.

2. Ketika halaman tidak full width, dan jari mencoba menggeser secara horizontal, seringkali malah keseluruhan halaman yang digeser, meskipun niat pengguna adalah scrolling pada code block. (Niat pengguna tidak sesuai dengan apa yang terjadi)

Penyelesaian:

1. Cari terlebih dahulu, penulisan LaTeX yang terlalu panjang secara horizontal. Sudah ditemukan, yaitu penulisan barisan (1.5, ...) di section "Apa itu barisan? (penjelasan tanpa kode)"

2. Edit penulisan LaTeX tersebut (markdown di file .ipynb/.qmd nya langsung) agar dipecah menjadi beberapa baris (agar melebar vertikal daripada melebar horizontal). Sudah dilakukan di file .ipynb modulnya, dengan memanfaatkan environment align. Lebih tepatnya, sudah dilakukan dalam commit berikut: 2c5665b18b927a6b64bd2d7e3977416ad85a7057

3. Render ulang Quarto project nya agar file .ipynb terbaru menjadi file .html terbaru untuk halaman ini. Sudah dilakukan, kali ini menggunakan `quarto preview`, dalam commit berikut: 2055de99e2e4b35df51a7168517eb5a9831a3879

4. Push kembali ke GitHub dari local. Sudah dilakukan

Status:

Seharusnya resolved, bisa tolong dicek lagi Zaki?

Kalau halaman modul 1 metnum 2024 genap sudah aman, mungkin issue yang ini bisa ditutup dulu. Nanti kalau ada halaman dengan LaTeX yang terlalu panjang lagi, bisa buka issue baru (atau bahkan langsung diperbaiki kalo udah ngerti Git, GitHub & Quarto hehe)
